# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSGu8KURTNr90Un6yQzVxjWlIxaQw9pc
"""

import streamlit as st

st.set_page_config(page_title="Adama Notebooks", page_icon="📒")
st.title("📒 Internal Lab Portal - View Notebooks in Google Colab")
st.write("Select the relevant notebook by category. Clicking will open it in Google Colab.")

# GitHub information
GITHUB_USER = "omerburst"
REPO_NAME = "Adama"
BASE_COLAB_URL = f"https://colab.research.google.com/github/{GITHUB_USER}/{REPO_NAME}/blob/main"

# Notebook structure with updated English folder names
notebooks = {
    "AvirTochMivni": [
        ("Alchem_AvirTochMivni_results", "LabResults/AvirTochMivni/Alchem_AvirTochMivni_results.ipynb"),
    ],
    "GasKarka": [
        ("Alchem_soilgas_results_(Vr_2)", "LabResults/GasKarka/Alchem_soilgas_results_(Vr_2).ipynb"),
    ],
    "NiturMeiTehom": [
        ("bactochem_groundwater_results_(Vr_4)", "LabResults/NiturMeiTehom/bactochem_groundwater_results_(Vr_4).ipynb"),
    ],
    "SekerKarka": [
        ("Alchem_soil_results_(Vr_4)", "LabResults/SekerKarka/Alchem_soil_results_(Vr_4).ipynb"),
        ("KTE_soil_results", "LabResults/SekerKarka/KTE_soil_results.ipynb"),
        ("Machon_Haneft_soil_results_(Vr_4)", "LabResults/SekerKarka/Machon_Haneft_soil_results_(Vr_4).ipynb"),
    ]
}

# Display sections
for section, files in notebooks.items():
    st.header(section)
    for title, path in files:
        url = f"{BASE_COLAB_URL}/{path}"
        st.markdown(f"- [{title}]({url}) [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({url})")