# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ad7Iqe8TzOnrbaF2Y0WgCBhagBleO_gM
"""

import streamlit as st

# --- Page Config ---
st.set_page_config(page_title="Adama Lab Results Notebooks", page_icon="🔬")

# --- Logo and Title ---
# Center logo using st.image and custom title below
st.image("AdamaLogo.png", width=250)

st.markdown(
    """
    <div style="text-align: center;">
        <h1 style='margin-top: 10px;'>Adama – Lab Results Notebook Portal</h1>
        <p style='font-size:18px;'>Select the relevant notebook by category. Clicking will open it in Google Colab.</p>
    </div>
    <hr style="margin-top: 30px;"/>
    """,
    unsafe_allow_html=True
)

# --- GitHub Info ---
GITHUB_USER = "omerburst"
REPO_NAME = "Adama"
BASE_COLAB_URL = f"https://colab.research.google.com/github/{GITHUB_USER}/{REPO_NAME}/blob/main"

# --- Notebooks Dictionary ---
notebooks = {
    "SekerKarka": [
        ("Alchem_soil_results_(Vr_5)", "LabResults/SekerKarka/Alchem_soil_results_(Vr_5).ipynb"),
        ("KTE_soil_results", "LabResults/SekerKarka/KTE_soil_results.ipynb"),
        ("Machon_Haneft_soil_results_(Vr_4)", "LabResults/SekerKarka/Machon_Haneft_soil_results_(Vr_4).ipynb"),
    ],
    "GasKarka": [
        ("Alchem_soilgas_results_(Vr_2)", "LabResults/GasKarka/Alchem_soilgas_results_(Vr_2).ipynb"),
    ],
    "AvirTochMivni": [
        ("Alchem_AvirTochMivni_results", "LabResults/AvirTochMivni/Alchem_AvirTochMivni_results.ipynb"),
    ],
    "NiturMeiTehom": [
        ("bactochem_groundwater_results_(Vr_4)", "LabResults/NiturMeiTehom/bactochem_groundwater_results_(Vr_4).ipynb"),
    ]
}

# --- Display Sections Neatly ---
for section, files in notebooks.items():
    st.markdown(f"<h2 style='color:#2E3B4E;'>{section}</h2>", unsafe_allow_html=True)
    for title, path in files:
        url = f"{BASE_COLAB_URL}/{path}"
        st.markdown(f"""
        <div style="background-color: #f0f4f8; padding: 10px; border-radius: 10px; margin-bottom: 10px;">
            <a href="{url}" target="_blank" style="text-decoration: none; font-weight: bold; color: #003366;">
                📄 {title}
            </a><br/>
            <a href="{url}" target="_blank">
                <img src="https://colab.research.google.com/assets/colab-badge.svg" style="margin-top: 5px;"/>
            </a>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("<hr style='margin-top: 30px; margin-bottom: 30px;'/>", unsafe_allow_html=True)
