# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSGu8KURTNr90Un6yQzVxjWlIxaQw9pc
"""

import streamlit as st

st.set_page_config(page_title="Adama Notebooks", page_icon="📒")
st.title("📒 פורטל פנימי - מחברת קוד לצפייה ב-Colab")
st.write("בחר את המחברת הרלוונטית לפי התחום. לחיצה תפתח אותה ב-Google Colab.")

# GitHub information
GITHUB_USER = "omerburst"
REPO_NAME = "Adama"
BASE_COLAB_URL = f"https://colab.research.google.com/github/{GITHUB_USER}/{REPO_NAME}/blob/main"

# Notebook structure
notebooks = {
    "אוויר תוך מבני": [
        ("Alchem_AvirTochMivni_results", "עיבוד נתונים/אוויר תוך מבני/Alchem_AvirTochMivni_results.ipynb"),
    ],
    "גז קרקע": [
        ("Alchem_soilgas_results_(Vr_2)", "עיבוד נתונים/גז קרקע/Alchem_soilgas_results_(Vr_2).ipynb"),
    ],
    "ניטור מי תהום": [
        ("bactochem_groundwater_results_(Vr_4)", "עיבוד נתונים/ניטור מי תהום/bactochem_groundwater_results_(Vr_4).ipynb"),
    ],
    "סקר קרקע": [
        ("Alchem_soil_results_(Vr_4)", "עיבוד נתונים/סקר קרקע/Alchem_soil_results_(Vr_4).ipynb"),
        ("KTE_soil_results", "עיבוד נתונים/סקר קרקע/KTE_soil_results.ipynb"),
        ("Machon_Haneft_soil_results_(Vr_4)", "עיבוד נתונים/סקר קרקע/Machon_Haneft_soil_results_(Vr_4).ipynb"),
    ]
}

# Display sections
for section, files in notebooks.items():
    st.header(section)
    for title, path in files:
        url = f"{BASE_COLAB_URL}/{path}"
        st.markdown(f"- [{title}]({url}) [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({url})")